version: 2
updates:
  # Enable version updates for npm (pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 10
    reviewers:
      - "khell"
    assignees:
      - "khell"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates together
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific dependencies that need manual updates
    ignore:
      # Ignore major version bumps for these critical packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]

  # Admin service dependencies
  - package-ecosystem: "npm"
    directory: "/services/ash-admin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    reviewers:
      - "khell"
    commit-message:
      prefix: "chore(admin-deps)"
    labels:
      - "dependencies"
      - "admin-service"

  # Portal service dependencies
  - package-ecosystem: "npm"
    directory: "/services/ash-portal"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    reviewers:
      - "khell"
    commit-message:
      prefix: "chore(portal-deps)"
    labels:
      - "dependencies"
      - "portal-service"

  # Database package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 3
    reviewers:
      - "khell"
    commit-message:
      prefix: "chore(db-deps)"
    labels:
      - "dependencies"
      - "database"
      - "critical"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    reviewers:
      - "khell"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci-cd"

  # Docker dependencies (if using Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 3
    reviewers:
      - "khell"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"
