# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # NPM dependencies for admin service
  - package-ecosystem: "npm"
    directory: "/services/ash-admin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 10
    reviewers:
      - "ash-ai/security-team"
    assignees:
      - "ash-ai/security-team"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore major version updates for Next.js (review manually)
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # NPM dependencies for portal service
  - package-ecosystem: "npm"
    directory: "/services/ash-portal"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 10
    reviewers:
      - "ash-ai/security-team"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"

  # NPM dependencies for database package
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    reviewers:
      - "ash-ai/security-team"
    labels:
      - "dependencies"
      - "database"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      # Ignore major Prisma updates (test thoroughly)
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    reviewers:
      - "ash-ai/security-team"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(ci)"

  # Docker (if using)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Manila"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
