[build]
  base = "services/ash-admin"
  command = "cd ../.. && pnpm install && pnpm --filter @ash/database prisma generate && pnpm --filter @ash/admin run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
