[build]
  base = "services/ash-admin"
  command = "cd ../.. && pnpm install --frozen-lockfile && cd packages/database && npx prisma generate && cd ../../services/ash-admin && pnpm add -D typescript@^5.0.0 @types/node@^20.0.0 && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
