[build]
  command = "pnpm install && pnpm --filter @ash/database prisma generate && cd services/ash-admin && pnpm run build"
  publish = "services/ash-admin/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
