packages:
  - 'packages/*'
  - 'services/*'

catalog:
  # Core dependencies
  typescript: ^5.4.0
  "@types/node": ^20.12.0
  
  # React ecosystem
  react: ^18.3.0
  react-dom: ^18.3.0
  "@types/react": ^18.3.0
  "@types/react-dom": ^18.3.0
  
  # Next.js
  next: ^14.2.0
  
  # Database & ORM
  prisma: ^5.12.0
  "@prisma/client": ^5.12.0
  
  # UI & Styling
  "@radix-ui/react-accordion": ^1.1.2
  "@radix-ui/react-alert-dialog": ^1.0.5
  "@radix-ui/react-avatar": ^1.0.4
  "@radix-ui/react-button": ^0.1.0
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-dropdown-menu": ^2.0.6
  "@radix-ui/react-form": ^0.1.8
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-popover": ^1.0.7
  "@radix-ui/react-select": ^2.0.0
  "@radix-ui/react-separator": ^1.0.3
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-tabs": ^1.0.4
  "@radix-ui/react-toast": ^1.1.5
  "@radix-ui/react-tooltip": ^1.0.7
  tailwindcss: ^3.4.0
  "class-variance-authority": ^0.7.0
  clsx: ^2.1.0
  "tailwind-merge": ^2.3.0
  "lucide-react": ^0.548.0
  
  # Forms & Validation
  "react-hook-form": ^7.51.0
  "@hookform/resolvers": ^3.3.0
  zod: ^3.23.0
  
  # State Management
  zustand: ^4.5.0
  "@tanstack/react-query": ^5.29.0
  
  # Authentication
  "next-auth": ^4.24.13
  "@auth/prisma-adapter": ^2.11.1
  
  # Utils & APIs
  axios: ^1.6.0
  date-fns: ^3.6.0
  nanoid: ^5.0.4
  
  # Development
  "@turbo/gen": ^2.0.0
  turbo: ^2.0.0
  eslint: ^8.57.0
  prettier: ^3.2.0
  "@typescript-eslint/eslint-plugin": ^7.0.0
  "@typescript-eslint/parser": ^7.0.0
  "eslint-config-next": ^14.2.0
  "eslint-config-prettier": ^9.1.0
  "eslint-config-turbo": ^2.0.0