[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && cd packages/database && npx prisma generate && cd ../../services/ash-admin && pnpm run build"

[deploy]
startCommand = "cd services/ash-admin && pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "ashley-ai-admin"
workingDirectory = "/"
