import { Response } from 'express';
import { AuthenticatedRequest } from '../middleware/auth';
import multer from 'multer';
export declare const upload: multer.Multer;
export declare const getDesignAssets: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
export declare const getDesignAsset: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
export declare const uploadDesignAssets: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
export declare const approveDesignAsset: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
export declare const createDesignVersion: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
export declare const getClientApprovalLink: (req: AuthenticatedRequest, res: Response) => Promise<Response<any, Record<string, any>>>;
