import { EventEmitter } from "eventemitter3";
import { z } from "zod";
import { PrismaClient } from "@ash-ai/database";
import type { FileValidationResult } from "./types";
declare const FileValidationSchema: z.ZodObject<{
    workspaceId: z.ZodString;
    designVersionId: z.ZodString;
    fileUrl: z.ZodString;
    fileName: z.ZodString;
    fileType: z.ZodEnum<["AI", "PSD", "PNG", "JPG", "SVG", "PDF", "DST", "EPS"]>;
    printMethod: z.ZodEnum<["SILKSCREEN", "DTG", "SUBLIMATION", "EMBROIDERY", "HEAT_TRANSFER"]>;
    validationRules: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    workspaceId?: string;
    designVersionId?: string;
    fileUrl?: string;
    fileName?: string;
    fileType?: "AI" | "PSD" | "PNG" | "JPG" | "SVG" | "PDF" | "DST" | "EPS";
    printMethod?: "SILKSCREEN" | "SUBLIMATION" | "EMBROIDERY" | "DTG" | "HEAT_TRANSFER";
    validationRules?: string[];
}, {
    workspaceId?: string;
    designVersionId?: string;
    fileUrl?: string;
    fileName?: string;
    fileType?: "AI" | "PSD" | "PNG" | "JPG" | "SVG" | "PDF" | "DST" | "EPS";
    printMethod?: "SILKSCREEN" | "SUBLIMATION" | "EMBROIDERY" | "DTG" | "HEAT_TRANSFER";
    validationRules?: string[];
}>;
export declare class DesignFileValidationSystem extends EventEmitter {
    private db;
    private validationRules;
    constructor(db: PrismaClient);
    private setupEventHandlers;
    private initializeValidationRules;
    private addValidationRule;
    validateDesignFile(data: z.infer<typeof FileValidationSchema>): Promise<{
        validation: {
            id: string;
            workspace_id: string;
            created_at: Date;
            updated_at: Date;
            ashley_analysis: string | null;
            file_url: string;
            file_type: string;
            file_size: number;
            validation_status: string;
            validation_results: string | null;
            issues_found: string | null;
            auto_corrections: string | null;
            color_profile: string | null;
            resolution_dpi: number | null;
            dimensions: string | null;
            color_count: number | null;
            print_ready: boolean;
            estimated_cost: number | null;
            processed_at: Date | null;
            design_version_id: string;
        };
        result: FileValidationResult;
    }>;
    private performValidation;
    private extractFileMetadata;
    private getColorMode;
    private getApplicableRules;
    private applyValidationRule;
    private validateResolution;
    private validateFileFormat;
    private validateColorMode;
    private validateDimensions;
    private validatePrintSpecs;
    getValidationHistory(designVersionId: string): Promise<{
        id: string;
        workspace_id: string;
        created_at: Date;
        updated_at: Date;
        ashley_analysis: string | null;
        file_url: string;
        file_type: string;
        file_size: number;
        validation_status: string;
        validation_results: string | null;
        issues_found: string | null;
        auto_corrections: string | null;
        color_profile: string | null;
        resolution_dpi: number | null;
        dimensions: string | null;
        color_count: number | null;
        print_ready: boolean;
        estimated_cost: number | null;
        processed_at: Date | null;
        design_version_id: string;
    }[]>;
    revalidateFile(validationId: string): Promise<{
        validation: {
            id: string;
            workspace_id: string;
            created_at: Date;
            updated_at: Date;
            ashley_analysis: string | null;
            file_url: string;
            file_type: string;
            file_size: number;
            validation_status: string;
            validation_results: string | null;
            issues_found: string | null;
            auto_corrections: string | null;
            color_profile: string | null;
            resolution_dpi: number | null;
            dimensions: string | null;
            color_count: number | null;
            print_ready: boolean;
            estimated_cost: number | null;
            processed_at: Date | null;
            design_version_id: string;
        };
        result: FileValidationResult;
    }>;
    private handleValidationStarted;
    private handleValidationCompleted;
    private handleValidationFailed;
}
export {};
